### ISSUE TITLE
Support exclude filtering by tag

### ISSUE THREAD

**Issue by rkj** [jotaen/klog#187]
Would be nice if report could total all the activity excluding some with specific tag(s), e.g.:

    9:00 - 9:30 #project1 do some work
    9:30 - 10:00 #break
    10:00 - 10:30 #project2 some other work

and then doing something like

    $ klog report --tags=-break

**Comment by rkj** [comment]
Oh my, this is fun one to do using json. Not super readable, but doable:
```bash
  klog json --today | jq '.records[-1].total_mins as $total |
    (.records[-1].entries | map(select(.tags[] | contains("home") or contains("break"))) |
    [.[].total_mins] | add) as $personal |
    ($total - $personal) as $time |
    "\($time / 60 | floor)h\($time % 60)m"
  '
```

It would be nice if was natively supported, but this is ok too.

**Comment by jotaen** [comment]
Thanks for your thoughts, and cool that you were able to work around via `klog json` for now.

I think this is a broader topic, so I’ve created https://github.com/jotaen/klog/discussions/190 for a place to discuss ideas and approaches.

**Comment by rkj** [comment]
Thanks @jotaen!

Here is more readable version of my script:
```
# Prints how much work time happened today.
work() {
  klog json "$@" |
    jq '
      def fmt_time($mins): "\($mins / 60 | floor)h\($mins % 60)m";
      def with_tags: map(select(.tags[] | contains("home") or contains("break")));
      .records[] |
      {
        date: .date,
        total: .total_mins,
        personal: .entries | with_tags | [.[].total_mins] | add
      } |
        "\(.date): \(fmt_time(.total - .personal))"
  '
}
```
it's not too bad, just not well integrated.
