### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by wAuner** [jotaen/klog#2]
The tool looks great, thank you for developing it! Looks like just what I've been looking for, I'll give it a try starting today.

**Comment by jotaen** [comment]
Glad to hear that, thank you! 😊

And please don’t hesitate to share your feedback. There is still a lot of work to be done and I’m happy to consider all thoughts and ideas that people run into.

(Will close this ticket for now, feel free to open new ones then.)

**Comment by justjosias** [comment]
I was going to say the same thing. I've been looking for something very similar to this to use to log times doing various tasks.

Thank you so much for writing this. It's an incredibly useful tool. :)

**Comment by jotaen** [comment]
Thank you very much (to both of you), that means a lot to me!
