### ISSUE TITLE
Add flag for setting a summary to the start/stop commands

### ISSUE THREAD

**Issue by jotaen** [jotaen/klog#36]
When tracking a time entry via `track` you can already specify an entry summary, e.g.:

```
klog track '1h washing dishes' chores.klg
```

In analogy to that the `start` and `stop` subcommands should also allow this. In contrast to `track`, however (where the entry text is mandatory) we must use named flags here, because otherwise there would be multiple optional positional arguments: `<summary>` and `<filename>`.

So for `start` it could be:

```
klog start --summary 'this and that' foo.klg
```

`stop` should be equivalent – however, the question is how klog should deal with an entry summary that is already present, e.g.:

```
2000-01-01
    15:00 - ? Foo bar baz
```

**Comment by tecunningham** [comment]
For the "stop" summary, I feel the most logical behaviour would be to append the summary to what's there already. If you overwrite it then there's a danger of accidental data loss. And if the user intends to replace the original summary, they can always use the right wording in the new summary, and do edits in a text editor.
