### ISSUE TITLE
Negative time ranges

### ISSUE THREAD

**Issue by jotaen** [jotaen/klog#43]
In analogy to tracking a negative duration (`-1h`) it could be useful to allow tracking “negative” time ranges, i.e. a specific period of time to be deduced from the total.

Syntax ideas:

```
2020-01-01
    8:00-17:00 Work
    -12:00-13:00 Lunch break
    -(12:00-13:00) Lunch break
    -[12:00-13:00] Lunch break
```

Currently favouring the `[]` syntax, as it’s more distinct from the should-total.

Source: https://github.com/jotaen/klog/issues/3

**Comment by acikek** [comment]
Why does it need to be wrapped in `()` or `[]`?

**Comment by jotaen** [comment]
My reasoning was for visual clarity. It’s not necessary from a technical point of view, but I feel that it might be too easy to overlook otherwise. I added the “naked” version as well in the example above, I’m also open to any other suggestion.

**Comment by vladdeSV** [comment]
I am in favor of wrapping in `()`, with the same reasoning as @jotaen:

> for visual clarity.

**Comment by vladdeSV** [comment]
How would whitespace be handled inside and before the parentheses?

Are the following okay?
```klog
2021-04-20
  -(0:00-1:00) foo
  -    ( 0:00   -      1:00  ) foo
```
