### ISSUE TITLE
klog icon

### ISSUE THREAD

**Issue by jotaen** [jotaen/klog#6]
Would be cool to have an custom icon for `.klg` files, e.g. to display in file browsers.

Thoughts and suggestions are welcome.

**Comment by jotaen** [comment]
Tada 🎉 
Variations here for download: https://klog.jotaen.net/logo/index.html

![klog logo](https://klog.jotaen.net/logo/klog-black.png)

cc @vladdeSV (https://github.com/vladdeSV/vscode-klog/issues/2)

**Comment by vladdeSV** [comment]
Looks amazing! 🔥

**Comment by charisseysabel** [comment]
You're welcome 🤝
